"""reactions and dm reply

Revision ID: 2529f26ce839
Revises: 4f99d764d4ef
Create Date: 2026-06-21 15:21:34.044892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2529f26ce839'
down_revision: Union[str, Sequence[str], None] = '4f99d764d4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_reaction')
    )
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reactions_message_id'), ['message_id'], unique=False)

    # SQLite no fuerza FKs; añadimos solo la columna (el FK en batch fallaría).
    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_to_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.drop_column('reply_to_id')

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reactions_message_id'))

    op.drop_table('reactions')
    # ### end Alembic commands ###
