"""user profile fields

Revision ID: 389ea53f5ff4
Revises: e0681e8811c9
Create Date: 2026-06-20 00:47:48.112802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389ea53f5ff4'
down_revision: Union[str, Sequence[str], None] = 'e0681e8811c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=280), nullable=True))
        batch_op.add_column(sa.Column('accent_color', sa.String(length=7), server_default='#d97a4a', nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=16), server_default='online', nullable=False))
        batch_op.add_column(sa.Column('custom_status', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('custom_status')
        batch_op.drop_column('status')
        batch_op.drop_column('accent_color')
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
