"""message edit and reply

Revision ID: 4f99d764d4ef
Revises: 70b8f4b35f67
Create Date: 2026-06-21 10:07:13.365970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f99d764d4ef'
down_revision: Union[str, Sequence[str], None] = '70b8f4b35f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite no fuerza FKs; añadimos solo las columnas (el FK auto-referencial
    # en modo batch falla con "Constraint must have a name").
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('reply_to_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('reply_to_id')
        batch_op.drop_column('edited_at')

    # ### end Alembic commands ###
